# Generated by Django 4.2.3 on 2023-08-01 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization_OrganizationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='organization',
            name='password',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='OrganizationProfile',
        ),
        migrations.AddField(
            model_name='organization_organizationcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organization_organizationcategory',
            name='organizationCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organization.organizationcategory'),
        ),
        migrations.AddField(
            model_name='organization',
            name='category',
            field=models.ManyToManyField(through='organization.Organization_OrganizationCategory', to='organization.organizationcategory'),
        ),
    ]
