# Generated by Django 4.2.3 on 2023-08-01 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_is_deleted'),
        ('organization', '0002_organization_organizationcategory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='category',
            new_name='categories',
        ),
        migrations.AlterField(
            model_name='organization',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Organization_Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Organization_Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='organization.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='admins',
            field=models.ManyToManyField(related_name='admin_organizations', through='organization.Organization_Admin', to='user.user'),
        ),
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(related_name='member_organizations', through='organization.Organization_Members', to='user.user'),
        ),
    ]
