# Generated by Django 4.2.3 on 2023-09-04 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("dataset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="PROFILE_USER", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=50, null=True)),
                (
                    "profile_pic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "background_pic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("username", models.CharField(max_length=100, null=True)),
                ("password_digest", models.CharField(max_length=50, null=True)),
                ("firstname", models.CharField(max_length=100, null=True)),
                ("lastname", models.CharField(max_length=100, null=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("about", models.CharField(blank=True, max_length=1000, null=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="User_Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tags",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="dataset.tag"
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "roles",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="user.role",
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="user.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "files",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="dataset.file"
                    ),
                ),
                (
                    "users",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="user.user"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="files",
            field=models.ManyToManyField(through="user.User_File", to="dataset.file"),
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(through="user.User_Role", to="user.role"),
        ),
        migrations.AddField(
            model_name="user",
            name="tags",
            field=models.ManyToManyField(through="user.User_Tag", to="dataset.tag"),
        ),
    ]
