class UserDoesNotExist(Exception):
    ...


class DatasetDoesNotExist(Exception):
    ...

class DatasetDoesNotExist(Exception):
    ...

class UserNotAuthorized(Exception):
    ...

class CommentDoesNotExist(Exception):
    ...