# Generated by Django 4.2.3 on 2023-08-18 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0005_dataset_like_user_like_delete_dataset_like_user_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(through='dataset.User_Like', to='dataset.like'),
        ),
    ]
