# Generated by Django 4.2.3 on 2023-07-31 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('user', '0010_dataset_addt_file_dataset_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatasetAddtFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('file_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='DatasetMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata_file', models.URLField(null=True)),
                ('metadata_title', models.CharField(max_length=100)),
                ('metadata_blurb', models.CharField(blank=True, max_length=1000, null=True)),
                ('metadata_source_link', models.URLField()),
                ('metadata_resource_type', models.CharField(max_length=50)),
                ('publisher', models.CharField(max_length=100)),
                ('maintainer', models.CharField(max_length=100)),
                ('license_link', models.URLField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_user', models.BooleanField(default=True)),
                ('org_contributor', models.BooleanField(default=False)),
                ('org_admin', models.BooleanField(default=False)),
                ('super_admin', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='dataset_comment',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset_comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dataset_datasetfile',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset_datasetfile',
            name='dataset_file',
        ),
        migrations.RemoveField(
            model_name='dataset_datasettag',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='dataset_datasettag',
            name='dataset_tag',
        ),
        migrations.RemoveField(
            model_name='dataset_metadata',
            name='dataset',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='org_admin_id',
        ),
        migrations.RemoveField(
            model_name='organization_adminuser',
            name='org_admin_id',
        ),
        migrations.RemoveField(
            model_name='organization_adminuser',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='organization_organizationcategory',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='organization_organizationcategory',
            name='organization_category',
        ),
        migrations.RemoveField(
            model_name='organization_profile',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_userrole',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_userrole',
            name='user_role',
        ),
        migrations.RemoveField(
            model_name='user',
            name='about',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='owner_organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.RESTRICT, to='organization.organization'),
        ),
        migrations.DeleteModel(
            name='Dataset_Addt_File',
        ),
        migrations.DeleteModel(
            name='Dataset_Comment',
        ),
        migrations.DeleteModel(
            name='Dataset_DatasetFile',
        ),
        migrations.DeleteModel(
            name='Dataset_DatasetTag',
        ),
        migrations.DeleteModel(
            name='Dataset_File',
        ),
        migrations.DeleteModel(
            name='Dataset_Metadata',
        ),
        migrations.DeleteModel(
            name='Dataset_Tag',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Organization_AdminUser',
        ),
        migrations.DeleteModel(
            name='Organization_Category',
        ),
        migrations.DeleteModel(
            name='Organization_OrganizationCategory',
        ),
        migrations.DeleteModel(
            name='Organization_Profile',
        ),
        migrations.DeleteModel(
            name='User_Profile',
        ),
        migrations.DeleteModel(
            name='User_Role',
        ),
        migrations.DeleteModel(
            name='User_UserRole',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.user'),
        ),
        migrations.AddField(
            model_name='datasetmetadata',
            name='dataset',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='user.dataset'),
        ),
        migrations.AddField(
            model_name='datasetcomment',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.dataset'),
        ),
        migrations.AddField(
            model_name='datasetcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user'),
        ),
        migrations.AddField(
            model_name='datasetaddtfile',
            name='DatasetFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.datasetfile'),
        ),
    ]
