# Generated by Django 4.2.3 on 2023-08-01 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_user_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserRole', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.userrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(through='user.User_UserRole', to='user.userrole'),
        ),
    ]
