# Generated by Django 4.2.3 on 2023-08-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_userrole_user_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
