# Generated by Django 4.2.3 on 2023-08-11 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_user_background_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='password_digest',
        ),
    ]
