# Generated by Django 4.2.3 on 2023-08-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_rename_password_user_password_digest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_pic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
