# Generated by Django 4.2.3 on 2023-08-11 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_background_pic_alter_user_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_userrole',
            old_name='UserRole',
            new_name='user_role',
        ),
    ]
