# Generated by Django 4.2.2 on 2023-08-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0019_rename_userrole_user_userrole_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
